version: "3"

services:
  postgresql:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: batch
      TZ: "Asia/Tokyo"
    hostname: postgres
    restart: always
    user: root

volumes:
  data: